version: "3.9"

services:
  krakend-gateway:
    image: devopsfaith/krakend
    container_name: kraken
    restart: always
    environment:
      - FIREBASE_PROJECT_ID=${FIREBASE_PROJECT_ID}
      - PORT=${PORT}
    networks:
      - app-network
    ports:
      - "${PORT}:${PORT}"
    volumes:
      - ./krakend.json:/etc/krakend/krakend.json:ro
    command: ["run", "-c", "/etc/krakend/krakend.json", "-p", "${PORT}"]

networks:
  app-network:
    external: true