version: "3.8"

services:
  krakend:
    build:
      context: ./krakend
      dockerfile: Dockerfile
    ports:
      - "${PORT}:${PORT}"
    volumes:
      - ./krakend/krakend.tmpl.json:/etc/krakend/krakend.tmpl.json:ro
    environment:
      - PORT=${PORT}
      - FIREBASE_JWK_URL=${FIREBASE_JWK_URL}
      - FIREBASE_PROJECT_ID=${FIREBASE_PROJECT_ID}
      - FIREBASE_ISSUER=${FIREBASE_ISSUER}
    networks:
      - app-network

networks:
  app-network:
    external: true